services:
    # Frontend estático
    - type: web
      name: orion-pdv-frontend
      env: static
      buildCommand: echo "Nothing to build"
      staticPublishPath: ./
      routes:
        - type: rewrite
          source: /*
          destination: /index.html
      headers:
        - path: /*
          name: Cache-Control
          value: no-cache

    # Backend API
    - type: web
      name: orion-pdv-api
      env: python
      buildCommand: pip install -r api/requirements.txt
      startCommand: cd api && gunicorn app:app
      envVars:
        - key: DB_HOST
          value: 34.95.140.152
        - key: DB_USER
          value: orion_app
        - key: DB_PASSWORD
          value: 123456
        - key: DB_NAME
          value: orion_pdv
        - key: DB_PORT
          value: 5432
        - key: SECRET_KEY
          generateValue: true
            startCommand: cd api && gunicorn app:app
      envVars:
        - key: DB_HOST
          value: 34.95.140.152
        - key: DB_USER
          value: orion_app
        - key: DB_PASSWORD
          value: 123456
        - key: DB_NAME
          value: orion_pdv
        - key: DB_PORT
          value: 5432
        - key: SECRET_KEY
          generateValue: true
